### PR TITLE
Add NGINX directive

### PR DESCRIPTION
**Pull request by algomaster99**

### CODE REVIEW

**Review by dhruvkb — COMMENTED** [review]
`[[...]]` is supposed to be for values that are different on the intranet and internet side. Is this true for `client_max_body_size` and timeouts?

**Comment by algomaster99** [comment]
@dhruvkb It is true for timeouts. I did that because IITR has a better network connection than an average household so naturally, we would want a higher timeout in case of internet.
No, it isn't true for `client_max_body_size`. We just wanted it customisable. @pradumangoyal

**Comment by dhruvkb** [comment]
I don't think increasing the NGINX timeout values is a solution for slow internet. These timeouts are for [NGINX <-> Gunicorn/Daphne communication](http://nginx.org/en/docs/http/ngx_http_proxy_module.html) which will be unaffected by the internet speed of the client.

**Comment by pradumangoyal** [comment]
@algomaster99 Agreed!

The main purpose is to have both values customisable. Even if they are same for internet and intranet, maintainers should have option to set some values while setting up their instance of Omniport. What are your views on this @dhruvkb ?

**Comment by dhruvkb** [comment]
I don't prefer a lot of values to be customisable because fewer variables means fewer differences between installations means fewer cases of "works on my setup". Then again, upload limit is a minor inconsequential thing so do whatever you want.

**Comment by algomaster99** [comment]
> I don't think increasing the NGINX timeout values is a solution for slow internet. These timeouts are for [NGINX <-> Gunicorn/Daphne communication](http://nginx.org/en/docs/http/ngx_http_proxy_module.html) which will be unaffected by the internet speed of the client.

Yes, I get that. But when uploading huge files if the NGINX doesn't receive a response from Gunicorn, it throws `502` so we have to adjust NGINX's timeout according to what we have set for Gunicorn.

**Comment by algomaster99** [comment]
> Then again, upload limit is a minor inconsequential thing so do whatever you want.

We have launched an app called RDrive (Courtesy of @ayu023ban and @gauransh7) which is supposed to be a google drive for IITR so uploading is necessary there.

**Comment by dhruvkb** [comment]
@algomaster99 use workers on separate threads for long tasks, else you'll block the thread for all users!

**Comment by algomaster99** [comment]
@dhruvkb I am not sure how that will help with uploading files. Can you elaborate?
We have already configured `145` workers in gunicorn.

**Comment by dhruvkb** [comment]
My bad, the timeout increase **_might_** still be needed. I'll withdraw my arguments against this 👍

**Comment by algomaster99** [comment]
@dhruvkb We although have to make uploading a background process (maybe via Websockets). The `file-manager` team has scheduled it for `v2`.

**Review by pradumangoyal — APPROVED** [review]

**Pull request merged**
